import { fabric } from 'fabric'

import './addAttr'
import './config'
import './run_canvas'
import './canvas'
import './walk'
import './param'
import './lib'
import './align'
import './group'
import './image'
import './gif'
import './bar'
import './trend'
import './chart'
import './button'
import './component'
import './open'
import './dynamic'
import './set'
import './util'
import './history'

export default fabric
